include: package:lints/recommended.yaml

linter:
  rules:
    # Additional rules for better code quality
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_const
    - unnecessary_new
