name: mesh_layer_dart
version: 0.1.0

description: Minimal Bluetooth Mesh cryptography and PDU utilities in Dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  pointycastle: ^3.9.1

dev_dependencies:
  test: ^1.24.0
